---
- name: cleanup the Azure resource group after test
  hosts: '{{azure_resource_group}}'
  connection: winrm

  tasks:
  - name: remove Azure resource group
    azure_rm_resourcegroup:
      name: '{{azure_resource_group}}'
      location: australiaeast
      state: absent
      force: yes
