---
- name: install iis
  hosts: '{{azure_resource_group}}'

<<<<<<< HEAD
  tasks:
  - name: Install IIS Web-Server with sub features and management tools
    win_feature:
      name: Web-Server
      state: present
      include_sub_features: True
      include_management_tools: True
    register: win_feature
=======
  win_roles:
    - Web-WebServer
    - Web-Common-Http
    - Web-Default-Doc
    - Web-Dir-Browsing
    - Web-Performance
    - Web-Http-Errors
    - Web-Static-Content
    - Web-Http-Errors
    - Web-Http-Redirect
    - Web-Http-Logging
    - Web-Log-Libraries
    - Web-ODBC-Logging
    - Web-Request-Monitor
    - Web-Request-Filter
    - Web-Stat-Compression
    - Web-Dyn-Compression
    - Web-Filtering
    - Web-Basic-Auth
    - Web-Client-Auth
    - Web-Digest-Auth
    - Web-Cert-Auth
    - Web-IP-Security
    - Web-Url-Auth
    - Web-Windows-Auth
    - Web-Basic-Auth
    - Web-ASPNET45
    - Web-Net-Ext45
    - Web-AppInit
    - Web-Asp-Net45
    - Web-ISAPI-Ext
    - Web-ISAPI-Filter
    - Web-Mgmt-Console
    - Web-Metabase
    - Web-Lgcy-Mgmt-Console
    - Web-Scripting-Tools
    - NET-WCF-HTTP-Activation45
    - Telnet-Client
>>>>>>> 1267a557b1c64d679471545d3aea139d64c3d11c
