---
- name: configure the Windows Server
  hosts: '{{azure_resource_group}}'
  connection: winrm

  tasks:
  - name: install_chocolatey
    win_chocolatey:
      name: "chocolatey"
      state: downgrade
      version: 0.10.11

  - name: install notepadplusplus
    win_chocolatey:
      name: notepadplusplus
      state: present

  - name: install googlechrome
    win_chocolatey:
      name: googlechrome
      state: present
      ignore_checksums: yes

  - name: install git
    win_chocolatey:
      name: git
      state: present

  - name: install filezilla
    win_chocolatey:
      name: filezilla
      state: present

  - name: install 7zip
    win_chocolatey:
      name: 7zip
      state: present

  - name: enable choco installs without prompts
    win_chocolatey_feature:
      name: allowGlobalConfirmation
      state: enabled

  - name: install kb3035131
    win_chocolatey:
      name: kb3035131
      state: present
      become: yes
      become_user: Administrator
      become_method: runas

  - name: install kb2919442
    win_chocolatey:
      name: kb2919442
      state: present
      become: yes
      become_user: Administrator
      become_method: runas

  - name: install kb2999226
    win_chocolatey:
      name: kb2999226
      state: present
      become: yes
      become_user: Administrator
      become_method: runas

  - name: install tortoisegit
    win_chocolatey:
      name: tortoisegit
      state: present
      become: yes
      become_user: Administrator
      become_method: runas

  - name: install ant
    win_chocolatey:
      name: ant
      state: present

  - name: install gradle
    win_chocolatey:
      name: gradle
      state: present

  - name: install silverlight4sdk
    win_chocolatey:
      name: silverlight4sdk
      state: present

  - name: install silverlight5sdk
    win_chocolatey:
      name: silverlight5sdk
      state: present

  - name: install nvm
    win_chocolatey:
      name: nvm
      state: present

  - name: reboot afer installs
    win_reboot:
