---
# This playbook installs powershell version 5

- name: Run powershell script
  hosts: '{{azure_resource_group}}'
  gather_facts: false
  tasks:
    - name: create directory for Ansible 
      win_file:
        path: C:\ansible\
        state: directory

    - name: install powershell 5.1
      win_copy:
        src: powershell_upgrade.ps1
        dest: C:/ansible/powershell_upgrade.ps1
      register: out

    - debug: var=out.stdout_lines

    - name: Run remote PowerShell Script
      win_shell: powershell.exe -ExecutionPolicy ByPass -File C:/ansible/powershell_upgrade.ps1

    - pause: minutes=1

    - win_reboot:
