---
- name: install windows update KB's
  hosts: '{{azure_resource_group}}'

  tasks:

  - name: Install only particular updates based on the KB numbers
    win_updates:
      category_name:
      - SecurityUpdates
      - CriticalUpdates
      - UpdateRollups
      whitelist:
      - KB4499151
      - KB3035131
      - KB2919442
      - KB2999226
      - KB4499408
      - KB890830
      - KB3185319
    - win_reboot:
